### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by VoipSip** [nnleaf/CentOS_ThinClient#5]
i'm using your script and the password of my server root is changed and i don't know what is the new password in your script for root and i don't want to lose my data on my server

**Comment by nnleaf** [comment]
The password has been encrypted in the script. You'll have to manually change the password in the ks.cfg script if you want to reimage.

**Comment by VoipSip** [comment]
what is the password encrypted  i can't login in my server say my real password is error and the password is changed

**Comment by nnleaf** [comment]
You'll have to reimage it and set your own password.

**Comment by VoipSip** [comment]
i'm not reimage any password or exchange on your script i just using without any exchange

**Comment by VoipSip** [comment]
this is your encrypted password  U2FsdGVkX1+IPWbhHzXcfKcvxgIym9LhfoEgihwOMB+YX979Q01D3YQm/MUap3GB what is the real password i think my root change by this password because i'm running your script without any update

**Comment by nnleaf** [comment]
If you ran it on your actual server, that's pretty much your fault. This is meant for fresh kickstart installs.

Sorry, good luck.

**Comment by VoipSip** [comment]
you don't know the password U2FsdGVkX1+IPWbhHzXcfKcvxgIym9LhfoEgihwOMB+YX979Q01D3YQm/MUap3GB
